// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MainPageValidationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void mainPageValidation() {
    driver.get("https://bluenotetherapeutics.com/");
    driver.manage().window().setSize(new Dimension(978, 867));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".pa3 > .br0"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".w-50-ns > .w-100")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".w-50-ns > .w-100"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".f1-l"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".f6:nth-child(1)")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".mw7 > .f2"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".w-100:nth-child(1) > .no-underline > .f4"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".w-100:nth-child(1) > .no-underline > .link"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".w-100:nth-child(1) > .no-underline > .link")).click();
    driver.close();
  }
}
